### ISSUE TITLE
Unhandled error event

### ISSUE THREAD

**Issue by gargleblaster** [Cloud9Trader/oanda-adapter#1] opened 2015-03-18 21:17 UTC
I am seeing these errors, which terminate my app, fairly frequently (roughly 20 in 24 hours):

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Parse Error
    at CleartextStream.socketOnData (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:513:12)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.write [as _write] (tls.js:368:25)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at EncryptedStream.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)
    at flow (_stream_readable.js:610:7)
    at Socket.pipeOnReadable (_stream_readable.js:642:5)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)

They are sometimes -- but not always -- preceded by some connectivity issues like this:

[WARN] OandaAdapter: No heartbeat received from prices stream for 10 seconds. Reconnecting.
[INFO]  HTTPS OUT stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=EUR_USD
[ERROR] HTTPS IN  stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=EUR_USD { [Error: socket hang up] code: 'ECONNRESET' }
[INFO]  HTTPS IN  api-fxpractice.oanda.com undefined GET /v1/accounts/xxx/positions
Wed Mar 18 2015 04:23:15 GMT-0400 (EDT) positions [{"instrument":"EUR_USD","units":10000,"side":"buy","avgPrice":1.0594}] ...
Wed Mar 18 2015 04:23:15 GMT-0400 (EDT) ...openPositions [{"instrument":"EUR_USD","units":10000,"side":"buy","avgPrice":1.0594}]
[ERROR] HTTPS IN  stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=EUR_USD : 400 undefined
[WARN] OandaAdapter: No heartbeat received from events stream for 20 seconds. Reconnecting.
[INFO]  HTTPS OUT stream-fxpractice.oanda.com undefined GET /v1/events
[INFO]  HTTPS IN  stream-fxpractice.oanda.com undefined GET /v1/events
[WARN] OandaAdapter: No heartbeat received from prices stream for 10 seconds. Reconnecting.
[INFO]  HTTPS OUT stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=EUR_USD
[ERROR] HTTPS IN  stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=EUR_USD : 400 undefined
[WARN] OandaAdapter: No heartbeat received from prices stream for 10 seconds. Reconnecting.
[INFO]  HTTPS OUT stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=EUR_USD
[ERROR] HTTPS IN  stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=EUR_USD : 400 undefined
[WARN] OandaAdapter: No heartbeat received from prices stream for 10 seconds. Reconnecting.
[INFO]  HTTPS OUT stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=EUR_USD

Any idea what's causing this?  The functionality of the module is great, but I need to stop it from terminating my application.

**Comment by gargleblaster** [comment] 2015-04-14 22:12
I know what causes this.  Oanda limits you to two streaming connections, and if you open a third, the oldest one gets closed.  This returns an error that throws this exception.  OandaAdapter should have a more graceful way of dealing with dropped connections, because it terminates the application.  I'm not sure there is a way for the application to wrap a try/catch around this.

**Comment by jonkafton** [comment] 2015-04-19 20:13
Have committed update so sockets will now be kept alive for as long as there are pending requests, so we are making full use of OANDA's rate limit of 15 requests per second. Max persistent connections is set to 2, so you shouldn't see any more errors caused by rate violation.

**Closed by jonkafton** 2015-04-19 20:13 UTC

**Comment by gargleblaster** [comment] 2015-04-27 14:03
Have you updated npm?  I see the same version number now as I already have.

**Comment by jonkafton** [comment] 2015-04-27 17:25
Yes, bumped to v0.1.11 on npm 8 days ago.

**Comment by gargleblaster** [comment] 2015-04-28 23:02
My problems seem to have multiplied with this change:

[INFO]  HTTPS OUT stream-fxpractice.oanda.com undefined GET /v1/events
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) AUD_JPY initializing...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) AUD_JPY about to subscribe to price...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) AUD_USD initializing...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) AUD_USD about to subscribe to price...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) EUR_GBP initializing...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) EUR_GBP about to subscribe to price...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) EUR_JPY initializing...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) EUR_JPY about to subscribe to price...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) EUR_USD initializing...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) EUR_USD about to subscribe to price...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) GBP_USD initializing...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) GBP_USD about to subscribe to price...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) NZD_USD initializing...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) NZD_USD about to subscribe to price...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) USD_CAD initializing...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) USD_CAD about to subscribe to price...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) USD_JPY initializing...
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) USD_JPY about to subscribe to price...
[INFO]  HTTPS OUT stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=314xxxx&instruments=AUD_JPY%2CAUD_USD%2CEUR_GBP%2CEUR_JPY%2CEUR_USD%2CGBP_USD%2CNZD_USD%2CUSD_CAD%2CUSD_JPY
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) AUD_JPY ^[[33mtick: {"instrument":"AUD_JPY","time":"2015-04-28T22:51:51.050Z","bid":95.242,"ask":95.274}^[[39m
[INFO]  HTTPS OUT api-fxpractice.oanda.com undefined GET /v1/accounts/314xxxx/positions
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) AUD_USD ^[[33mtick: {"instrument":"AUD_USD","time":"2015-04-28T22:51:50.851Z","bid":0.80139,"ask":0.80165}^[[39m
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) EUR_GBP ^[[33mtick: {"instrument":"EUR_GBP","time":"2015-04-28T22:52:35.559Z","bid":0.71537,"ask":0.71566}^[[39m
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) EUR_JPY ^[[33mtick: {"instrument":"EUR_JPY","time":"2015-04-28T22:50:52.768Z","bid":130.426,"ask":130.452}^[[39m
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) EUR_USD ^[[33mtick: {"instrument":"EUR_USD","time":"2015-04-28T22:50:46.046Z","bid":1.09743,"ask":1.09764}^[[39m
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) GBP_USD ^[[33mtick: {"instrument":"GBP_USD","time":"2015-04-28T22:52:18.766Z","bid":1.53373,"ask":1.53408}^[[39m
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) NZD_USD ^[[33mtick: {"instrument":"NZD_USD","time":"2015-04-28T22:52:25.058Z","bid":0.77319,"ask":0.77352}^[[39m
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) USD_CAD ^[[33mtick: {"instrument":"USD_CAD","time":"2015-04-28T22:52:35.049Z","bid":1.20303,"ask":1.20336}^[[39m
Tue Apr 28 2015 18:52:37 GMT-0400 (EDT) USD_JPY ^[[33mtick: {"instrument":"USD_JPY","time":"2015-04-28T22:51:30.335Z","bid":118.837,"ask":118.854}^[[39m
[INFO]  HTTPS OUT api-fxpractice.oanda.com undefined GET /v1/accounts/314xxxx/positions
[INFO]  HTTPS OUT api-fxpractice.oanda.com undefined GET /v1/accounts/314xxxx/positions
[INFO]  HTTPS IN  api-fxpractice.oanda.com undefined GET /v1/accounts/314xxxx/positions
[INFO] Socket pool for api-fxpractice.oanda.com:443 has 1 pending requests over 2 sockets
Tue Apr 28 2015 18:52:38 GMT-0400 (EDT) AUD_JPY positions [] ...
Tue Apr 28 2015 18:52:38 GMT-0400 (EDT) AUD_JPYdiscovered state IDLE
Tue Apr 28 2015 18:52:38 GMT-0400 (EDT) AUD_JPY...openPositions []
[INFO]  HTTPS IN  api-fxpractice.oanda.com undefined GET /v1/accounts/314xxxx/positions
Tue Apr 28 2015 18:52:38 GMT-0400 (EDT) AUD_USD positions [] ...
Tue Apr 28 2015 18:52:38 GMT-0400 (EDT) AUD_USDdiscovered state IDLE
Tue Apr 28 2015 18:52:38 GMT-0400 (EDT) AUD_USD...openPositions []
[INFO]  HTTPS IN  api-fxpractice.oanda.com undefined GET /v1/accounts/314xxxx/positions
Tue Apr 28 2015 18:52:38 GMT-0400 (EDT) EUR_GBP positions [] ...
Tue Apr 28 2015 18:52:38 GMT-0400 (EDT) EUR_GBPdiscovered state IDLE
Tue Apr 28 2015 18:52:38 GMT-0400 (EDT) EUR_GBP...openPositions []
[INFO]  HTTPS OUT api-fxpractice.oanda.com undefined GET /v1/accounts/314xxxx/positions
[INFO]  HTTPS OUT api-fxpractice.oanda.com undefined GET /v1/accounts/314xxxx/positions
[INFO]  HTTPS IN  api-fxpractice.oanda.com undefined GET /v1/accounts/314xxxx/positions
Tue Apr 28 2015 18:52:38 GMT-0400 (EDT) EUR_JPY positions [] ...
Tue Apr 28 2015 18:52:38 GMT-0400 (EDT) EUR_JPYdiscovered state IDLE
Tue Apr 28 2015 18:52:38 GMT-0400 (EDT) EUR_JPY...openPositions []

...

[WARN] OandaAdapter: No heartbeat received from prices stream for 10 seconds. Reconnecting.
[INFO]  HTTPS OUT stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=AUD_JPY%2CAUD_USD%2CEUR_GBP%2CEUR_JPY%2CEUR_USD%2CGBP_USD%2CNZD_USD%2CUSD_CAD%2CUSD_JPY
[WARN]  HTTPS IN  stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=314xxxx&instruments=AUD_JPY%2CAUD_USD%2CEUR_GBP%2CEUR_JPY%2CEUR_USD%2CGBP_USD%2CNZD_USD%2CUSD_CAD%2CUSD_JPY 898 Could not parse response body
[INFO]  HTTPS IN  stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=314xxxx&instruments=AUD_JPY%2CAUD_USD%2CEUR_GBP%2CEUR_JPY%2CEUR_USD%2CGBP_USD%2CNZD_USD%2CUSD_CAD%2CUSD_JPY
[ERROR] HTTPS IN  stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=AUD_JPY%2CAUD_USD%2CEUR_GBP%2CEUR_JPY%2CEUR_USD%2CGBP_USD%2CNZD_USD%2CUSD_CAD%2CUSD_JPY : 400 undefined
[WARN] OandaAdapter: No heartbeat received from prices stream for 10 seconds. Reconnecting.
[INFO]  HTTPS OUT stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=AUD_JPY%2CAUD_USD%2CEUR_GBP%2CEUR_JPY%2CEUR_USD%2CGBP_USD%2CNZD_USD%2CUSD_CAD%2CUSD_JPY
[ERROR] HTTPS IN  stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=AUD_JPY%2CAUD_USD%2CEUR_GBP%2CEUR_JPY%2CEUR_USD%2CGBP_USD%2CNZD_USD%2CUSD_CAD%2CUSD_JPY : 400 undefined
[WARN] OandaAdapter: No heartbeat received from prices stream for 10 seconds. Reconnecting.
[INFO]  HTTPS OUT stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=AUD_JPY%2CAUD_USD%2CEUR_GBP%2CEUR_JPY%2CEUR_USD%2CGBP_USD%2CNZD_USD%2CUSD_CAD%2CUSD_JPY
[ERROR] HTTPS IN  stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=AUD_JPY%2CAUD_USD%2CEUR_GBP%2CEUR_JPY%2CEUR_USD%2CGBP_USD%2CNZD_USD%2CUSD_CAD%2CUSD_JPY : 400 undefined
[WARN] OandaAdapter: No heartbeat received from prices stream for 10 seconds. Reconnecting.
[INFO]  HTTPS OUT stream-fxpractice.oanda.com undefined GET /v1/prices?accountId=undefined&instruments=AUD_JPY%2CAUD_USD%2CEUR_GBP%2CEUR_JPY%2CEUR_USD%2CGBP_USD%2CNZD_USD%2CUSD_CAD%2CUSD_JPY

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Parse Error
    at CleartextStream.socketOnData (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:513:12)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.write [as _write] (tls.js:368:25)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at EncryptedStream.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)
    at flow (_stream_readable.js:610:7)
    at Socket.pipeOnReadable (_stream_readable.js:642:5)
error: Forever detected script exited with code: 8
error: Script restart attempt #1
[INFO]  HTTPS OUT stream-fxpractice.oanda.com undefined GET /v1/events
Tue Apr 28 2015 18:53:18 GMT-0400 (EDT) AUD_JPY initializing...
Tue Apr 28 2015 18:53:18 GMT-0400 (EDT) AUD_JPY about to subscribe to price...
Tue Apr 28 2015 18:53:18 GMT-0400 (EDT) AUD_USD initializing...
Tue Apr 28 2015 18:53:18 GMT-0400 (EDT) AUD_USD about to subscribe to price...
Tue Apr 28 2015 18:53:18 GMT-0400 (EDT) EUR_GBP initializing...
Tue Apr 28 2015 18:53:18 GMT-0400 (EDT) EUR_GBP about to subscribe to price...
Tue Apr 28 2015 18:53:18 GMT-0400 (EDT) EUR_JPY initializing...
Tue Apr 28 2015 18:53:18 GMT-0400 (EDT) EUR_JPY about to subscribe to price...
Tue Apr 28 2015 18:53:18 GMT-0400 (EDT) EUR_USD initializing...

**Comment by jonkafton** [comment] 2015-07-09 19:15
Are you still having issues with this?
